### PR TITLE
fix(search) scroll bar strange behaviour

### LINKED ISSUE #73: Search: Scroll bar on the right behaves strangely. I think it doesn't end where it should.

### PR DESCRIPTION
**Pull request by dangeol**
Closes #73

### CODE REVIEW

File: digitalpalireader/content/js/dpr_pal.js [hunk 1]
```diff
@@ -99,13 +101,18 @@ console.log('Loading DPR_PAL...');
     }
   }
 
+  DPR_PAL.setPaliTextContentHeight = () => {
+    bottomFrameUp?$("#paliTextContent").addClass("COLLAPSE"):$("#paliTextContent").removeClass("COLLAPSE");
```
Comment (parthopdas) [inline digitalpalireader/content/js/dpr_pal.js]: Some spaces between the ? and the : would make it more readable.

File: digitalpalireader/content/js/dpr_pal.js [hunk 2]
```diff
@@ -117,8 +124,9 @@ console.log('Loading DPR_PAL...');
       $(bottomFrameSelector).slideToggle();
       if ($(bottomFrameSelector).is(":visible")) {
         $(".rotate").toggleClass("down");
-        $(".rotate").hasClass("down")?$("#paliTextContent").addClass("COLLAPSE"):$("#paliTextContent").removeClass("COLLAPSE");
+        $(".rotate").hasClass("down") ? bottomFrameUp=true : bottomFrameUp=false;
```
Comment (parthopdas) [inline digitalpalireader/content/js/dpr_pal.js]: It can be simplified to

```
bottomFrameUp = $(".rotate").hasClass("down");
```

Comment (parthopdas) [reply digitalpalireader/content/js/dpr_pal.js]: Even better I am wondering if instead of a variable bottomFrameUp, we can just have a function

```
BottomFrameUp = () => $(".rotate").hasClass("down");
```

File: digitalpalireader/content/js/xml.js [hunk 3]
```diff
@@ -964,26 +965,44 @@ function loadXMLindex(place,compare) {
...
 	// title, tab, link
 
 	document.getElementsByTagName('title')[0].innerHTML = tabT;
 
-
-
-
   if (DPR_PAL.isWeb){
     theDatao=digitalpalireader.makeWebAppropriate(theDatao);
+    $('#mafbc').append('<div id="paliTextContent">	'+theDatao+'</div>');
```
Comment (parthopdas) [inline digitalpalireader/content/js/xml.js]: This will require some all round testing. We can discuss this when we chat.

File: digitalpalireader/content/js/xml.js [hunk 4]
```diff
@@ -964,26 +965,44 @@ function loadXMLindex(place,compare) {
...
+    DPR_PAL.setPaliTextContentHeight();
+  } else {
+    // permalink
+    var permalink = `${DPR_PAL.dprHomePage}?`;
```
Comment (parthopdas) [inline digitalpalireader/content/js/xml.js]: This else case is of course a PITA. We'll get rid of all xul stuff right after alpha.

File: digitalpalireader/content/js/xml.js (hunk 3 above)
Comment (dangeol) [reply digitalpalireader/content/js/xml.js]: I'm not sure as this code had been there before, I just moved the line in the isWeb condition.

File: digitalpalireader/content/js/xml.js (hunk 4 above)
Comment (dangeol) [reply digitalpalireader/content/js/xml.js]: Ok

File: digitalpalireader/content/js/dpr_pal.js (hunk 1 above)
Comment (dangeol) [reply digitalpalireader/content/js/dpr_pal.js]: Changed

File: digitalpalireader/content/js/dpr_pal.js (hunk 2 above)
Comment (dangeol) [reply digitalpalireader/content/js/dpr_pal.js]: Good comment, I was also not happy with the variable. Changed it.

File: digitalpalireader/content/js/xml.js (hunk 4 above)
Comment (dangeol) [reply digitalpalireader/content/js/xml.js]: Ok

File: digitalpalireader/content/js/xml.js (hunk 3 above)
Comment (parthopdas) [reply digitalpalireader/content/js/xml.js]: i missed that. it is fine then
