### PR TITLE
fix(search) regex selection

### LINKED ISSUE #60: Search: RegEx not on par with DPRv1
Ticking RegEx check box or not makes no difference. 

Ensure the following cases work before closing this issue:
- āmi\b which should list hundreds of results -> this will be fixed by https://github.com/parthopdas/digitalpalireader/issues/56
- For example when searching for **arahan.\*** , it makes no difference whether Regex is checked or not. To be consistent with DPRv1, unticking RegEx should give no results for **arahan.\***

### PR DESCRIPTION
**Pull request by dangeol**
Closes #60

### CODE REVIEW

File: digitalpalireader/content/js/search.js [hunk 1]
```diff
@@ -467,6 +467,21 @@ function createTdForMatch(dups, match) {
 
 function createTables(xmlDoc,hiert)
 {
+  //TO DO (comment DO 2020-02-22): This is a temporary fix search for alpha release.
```
Comment (parthopdas) [inline digitalpalireader/content/js/search.js]: yep. this is one of the items i have put on backlog for beta.
